[green_agent]
agentbeats_id = "019bc0cd-8365-7ae2-8499-8d46332e06f6"
env = { LOG_LEVEL = "INFO" }

[[participants]]
#add your purple agent agnetbeats id here. Note:Please do not change purple agent name here leave it as: name = "purple"
agentbeats_id = "019bc0ce-e032-70c3-86ec-b62e2e527a22"
name = "purple"
env = { GEMINI_API_KEY = "${GEMINI_API_KEY}" }

[config]
# Add your assessment config here
